name: CI

on: [ push, pull_request ]

jobs:
  Build-by-Pyinstaller:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: amd64-win64-cli-pyinstaller-packaged, os: windows-latest, A: x64, build_type_a: cli, build_type_b: s, bit: 64 }
          - { name: amd64-win64-cli-pyinstaller-unpackaged, os: windows-latest, A: x64, build_type_a: cli, build_type_b: m, bit: 64 }
          - { name: amd64-win64-gui-pyinstaller-packaged,  os: windows-latest, A: x64, build_type_a: gui, build_type_b: s, bit: 64 }
          - { name: amd64-win64-gui-pyinstaller-unpackaged, os: windows-latest, A: x64, build_type_a: gui, build_type_b: m, bit: 64 }
          - { name: i386-win32-cli-pyinstaller-packaged, os: windows-latest, A: x86, build_type_a: cli, build_type_b: s, bit: 32 }
          - { name: i386-win32-cli-pyinstaller-unpackaged, os: windows-latest, A: x86, build_type_a: cli, build_type_b: m, bit: 32 }
          - { name: i386-win32-gui-pyinstaller-packaged,  os: windows-latest, A: x86, build_type_a: gui, build_type_b: s, bit: 32 }
          - { name: i386-win32-gui-pyinstaller-unpackaged, os: windows-latest, A: x86, build_type_a: gui, build_type_b: m, bit: 32 }
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download UPX
      uses: i3h/download-release-asset@v1.3.2
      with:
        owner: upx
        repo: upx
        tag: latest
        file: /upx-[0-9.]+-win${{ matrix.bit }}.zip/
        path: ./
    - name: Unzip UPX
      run: |
        Expand-Archive -Path ./upx-*.zip -DestinationPath ./
        Move-Item ./upx-*/upx.exe ./
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      shell: cmd
      run: |
        pip install pyinstaller pillow colorlog pycryptodome numpy
        if ${{ matrix.build_type_a }} == cli pip install progressbar2
        if ${{ matrix.build_type_a }} == gui pip install wxPython
    - name: Build artifacts
      shell: cmd
      run: |
        if ${{ matrix.build_type_a }} == cli if ${{ matrix.build_type_b }} == s pyinstaller -F Image_encryptor_cli.py
        if ${{ matrix.build_type_a }} == cli if ${{ matrix.build_type_b }} == m pyinstaller Image_encryptor_cli.py
        if ${{ matrix.build_type_a }} == gui if ${{ matrix.build_type_b }} == s pyinstaller -F Image_encryptor_gui.py
        if ${{ matrix.build_type_a }} == gui if ${{ matrix.build_type_b }} == m pyinstaller Image_encryptor_gui.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: dist
  Build-by-Nuitka:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: amd64-win64-cli-nuitka-msvc-14.2-packaged, os: windows-latest, C: msvc-14.2-x64, A: x64, build_type_a: cli, build_type_b: s }
          - { name: amd64-win64-cli-nuitka-msvc-14.2-unpackaged, os: windows-latest, C: msvc-14.2-x64, A: x64, build_type_a: cli, build_type_b: m }
          - { name: amd64-win64-gui-nuitka-msvc-14.2-packaged,  os: windows-latest, C: msvc-14.2-x64, A: x64, build_type_a: gui, build_type_b: s }
          - { name: amd64-win64-gui-nuitka-msvc-14.2-unpackaged, os: windows-latest, C: msvc-14.2-x64, A: x64, build_type_a: gui, build_type_b: m }
          - { name: i386-win32-cli-nuitka-msvc-14.2-packaged, os: windows-latest, C: msvc-14.2-x86, A: x86, build_type_a: cli, build_type_b: s }
          - { name: i386-win32-cli-nuitka-msvc-14.2-unpackaged, os: windows-latest, C: msvc-14.2-x86, A: x86, build_type_a: cli, build_type_b: m }
          - { name: i386-win32-gui-nuitka-msvc-14.2-packaged,  os: windows-latest, C: msvc-14.2-x86, A: x86, build_type_a: gui, build_type_b: s }
          - { name: i386-win32-gui-nuitka-msvc-14.2-unpackaged, os: windows-latest, C: msvc-14.2-x86, A: x86, build_type_a: gui, build_type_b: m }
    runs-on: windows-latest
    steps:
    - name: 'Set up Developer Command Prompt'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.A }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      shell: cmd
      run: |
        pip install pillow colorlog pycryptodome numpy zstandard
        if ${{ matrix.build_type_a }} == cli pip install progressbar2
        if ${{ matrix.build_type_a }} == gui pip install wxPython
        pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
    - name: Build artifacts
      shell: cmd
      run: |
        mkdir nuitka
        if ${{ matrix.build_type_a }} == cli if ${{ matrix.build_type_b }} == s nuitka --msvc=latest --lto=yes --onefile --assume-yes-for-downloads --plugin-enable=numpy,multiprocessing --output-dir=%H%/nuitka --remove-output %H%/Image_encryptor_cli.py
        if ${{ matrix.build_type_a }} == cli if ${{ matrix.build_type_b }} == m nuitka --msvc=latest --lto=yes --standalone --assume-yes-for-downloads --plugin-enable=numpy,multiprocessing --output-dir=%H%/nuitka --remove-output %H%/Image_encryptor_cli.py
        if ${{ matrix.build_type_a }} == gui if ${{ matrix.build_type_b }} == s nuitka --msvc=latest --lto=yes --onefile --assume-yes-for-downloads --plugin-enable=numpy,multiprocessing --output-dir=%H%/nuitka --remove-output %H%/Image_encryptor_gui.py
        if ${{ matrix.build_type_a }} == gui if ${{ matrix.build_type_b }} == m nuitka --msvc=latest --lto=yes --standalone --assume-yes-for-downloads --plugin-enable=numpy,multiprocessing --output-dir=%H%/nuitka --remove-output %H%/Image_encryptor_gui.py
    run: |
        nuitka --msvc=latest --lto=yes --onefile --assume-yes-for-downloads --plugin-enable=numpy,multiprocessing --output-dir=nuitka --remove-output Image_encryptor_cli.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: build
