name: CI

on: [ push, pull_request ]

jobs:
  Build-by-Pyinstaller:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: amd64-win64-cli-pyinstaller-packaged, os: windows-latest, A: x64, build_type_b: s, bit: 64 }
          - { name: amd64-win64-cli-pyinstaller-unpackaged, os: windows-latest, A: x64, build_type_b: m, bit: 64 }
          - { name: i386-win32-cli-pyinstaller-packaged, os: windows-latest, A: x86, build_type_b: s, bit: 32 }
          - { name: i386-win32-cli-pyinstaller-unpackaged, os: windows-latest, A: x86, build_type_b: m, bit: 32 }
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download UPX
      uses: i3h/download-release-asset@v1.3.2
      with:
        owner: upx
        repo: upx
        tag: latest
        file: /upx-[0-9.]+-win${{ matrix.bit }}.zip/
        path: ./
    - name: Unzip UPX
      run: |
        Expand-Archive -Path ./upx-*.zip -DestinationPath ./
        Move-Item ./upx-*/upx.exe ./
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      shell: cmd
      run: |
        pip install pyinstaller pillow colorlog pycryptodome progressbar2
    - name: Build artifacts
      shell: cmd
      run: |
        if ${{ matrix.build_type_b }} == s pyinstaller --exclude-module=setuptools,pyinstaller,altgraph -F Image_encryptor.py
        if ${{ matrix.build_type_b }} == m pyinstaller --exclude-module=setuptools,pyinstaller,altgraph Image_encryptor.py
    - name: Basic tests
      shell: cmd
      run: |
        cd dist
        if ${{ matrix.build_type_b }} == m (xcopy /y /s /h .\Image_encryptor\* .\) & (rd /s /q .\Image_encryptor)
        Image_encryptor.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: dist
  Build-by-Nuitka:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: amd64-win64-cli-nuitka-msvc-14.2-packaged, os: windows-latest, C: msvc-14.2-x64, A: x64, build_type_b: s }
          - { name: amd64-win64-cli-nuitka-msvc-14.2-unpackaged, os: windows-latest, C: msvc-14.2-x64, A: x64, build_type_b: m }
          - { name: i386-win32-cli-nuitka-msvc-14.2-packaged, os: windows-latest, C: msvc-14.2-x86, A: x86, build_type_b: s }
          - { name: i386-win32-cli-nuitka-msvc-14.2-unpackaged, os: windows-latest, C: msvc-14.2-x86, A: x86, build_type_b: m }
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Developer Command Prompt'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.A }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      shell: cmd
      run: |
        pip install pillow colorlog pycryptodome zstandard markupsafe progressbar2
        pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
    - name: Build artifacts
      shell: cmd
      run: |
        mkdir nuitka
        if ${{ matrix.build_type_b }} == s nuitka --msvc=latest --lto=yes --onefile --assume-yes-for-downloads --plugin-enable=multiprocessing --output-dir=nuitka --remove-output Image_encryptor.py
        if ${{ matrix.build_type_b }} == m nuitka --msvc=latest --lto=yes --standalone --assume-yes-for-downloads --plugin-enable=multiprocessing --output-dir=nuitka --remove-output Image_encryptor.py
    - name: Basic tests
      shell: cmd
      run: |
        cd nuitka
        if ${{ matrix.build_type_b }} == m (xcopy /y /s /h .\Image_encryptor.dist\* .\) & (rd /s /q .\Image_encryptor.dist)
        Image_encryptor.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: nuitka
